### PR TITLE
inconsistent space in postings and optional space in posting cost

### PR DESCRIPTION
**Pull request by Kilerd**
## Summary by CodeRabbit

- **New Features**
	- Added support for Python setup in the testing and publishing workflows.
	- Introduced new configuration options for operating currency, set to "CNY" (Chinese Yuan), and opened relevant accounts.
	- Enhanced transaction handling with improved metadata processing and document upload functionality.

- **Bug Fixes**
	- Streamlined transaction parsing logic by removing unnecessary metadata handling, improving clarity and efficiency.

- **Documentation**
	- New validation rules added for API responses to ensure data integrity.

- **Tests**
	- Updated test cases to reflect changes in transaction metadata handling and validations.

### CODE REVIEW

**Comment by Harry-Chen** [comment]
These test cases look enough to me. Maybe I would add some comments in the `inconsistent-indent-for-posting` case.

BTW, you spelled "consistent" wrong.

**Comment by Kilerd** [comment]
> These test cases look enough to me. Maybe I would add some comments in the `inconsistent-indent-for-posting` case.
> 
> BTW, you spelled "consistent" wrong.

sure, np

**Comment by Kilerd** [comment]
@coderabbit review

**Comment by Kilerd** [comment]
@coderabbit review

**Pull request merged**
