### PR TITLE
add `.beancount` file extension support

### PR DESCRIPTION
**Pull request by imWildCat**
`.beancount` is also widely used, including in the official repo.

## Summary by CodeRabbit

- **New Features**
  - Added support for the `.beancount` file extension, enhancing file compatibility for the beancount processor.

### CODE REVIEW

**Comment by imWildCat** [comment]
@coderabbitai review

**Comment by imWildCat** [comment]
Hi @Kilerd, could you please take a look? Thanks!

**Comment by Kilerd** [comment]
LGTM, I will merge it after the CI is pass

**Comment by Kilerd** [comment]
Hey @imWildCat, do you mind to fix the error reported by clippy?

**Comment by imWildCat** [comment]
```
error: doc list item missing indentation
Error:    --> zhang-ast/src/data.rs:174:9
    |
174 |     /// 2.1 return `unit * cost`, if cost is present
    |         ^
    |
    = help: if this is supposed to be its own paragraph, add a blank line
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation
    = note: `-D clippy::doc-lazy-continuation` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::doc_lazy_continuation)]`
help: indent this line
    |
174 |     ///    2.1 return `unit * cost`, if cost is present
    |         +++

error: doc list item missing indentation
Error:    --> zhang-ast/src/data.rs:175:9
    |
175 |     /// 2.2 return `unit * single_price`, if single price is present
    |         ^
    |
    = help: if this is supposed to be its own paragraph, add a blank line
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation
help: indent this line
    |
175 |     ///    2.2 return `unit * single_price`, if single price is present
    |         +++

error: doc list item missing indentation
Error:    --> zhang-ast/src/data.rs:176:9
    |
176 |     /// 2.3 return `total_price`, if total price is present
    |         ^
    |
    = help: if this is supposed to be its own paragraph, add a blank line
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation
help: indent this line
    |
176 |     ///    2.3 return `total_price`, if total price is present
    |         +++

error: doc list item missing indentation
Error:    --> zhang-ast/src/data.rs:177:9
    |
177 |     /// 2.4 return `unit`, if both cost and price are not present.
    |         ^
    |
    = help: if this is supposed to be its own paragraph, add a blank line
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation
help: indent this line
    |
177 |     ///    2.4 return `unit`, if both cost and price are not present.
    |         +++

error: could not compile `zhang-ast` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
```

seems not related to my change?

I'm not sure how to fix

**Comment by Kilerd** [comment]
seems like clippy introduce some new rules, don't worry I will fix it later.

**Comment by imWildCat** [comment]
thanks! you might want to enable squash merge btw

**Pull request merged**
