### PR TITLE
Some updates on building & CI

### PR DESCRIPTION
**Pull request by Harry-Chen**
Please refer to each commit for details, and [my-repo](https://github.com/Harry-Chen/zhang/actions) for action results.

Almost everything runs well, except that:

1.  'coverage' in Developer Build fails but I cannot reproduce.
2. Some steps need secrets in this repo.

Maybe you can merge them (not necessarily master) and try to fix the remaining problems.

### CODE REVIEW

**Comment by Kilerd** [comment]
seems like some of changes break the test.

**Comment by Harry-Chen** [comment]
> seems like some of changes break the test.

All tests pass on my machine. I am trying to reproduce & fix.

**Comment by Harry-Chen** [comment]
> seems like some of changes break the test.

Actually the test itself uses `BigDecimal` inappropriately and happened to work with earlier versions (it might round the number generated from inaccurate `f32` literal). It is fixed and all tests pass now.

**Comment by Harry-Chen** [comment]
> all tests pass, pls resolve the conflicts(from the PR of beancount parser's arithmetic syntax) and the error from fmt, then I can merge this change.

Now all checks have passed, including the coverage test.

**Pull request merged**
